filebeat.modules:
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.8/filebeat-module-activemq.html
- module: activemq
  audit:
    enabled: true
    var.paths:
      - /var/log/activemq/audit.log
  log:
    enabled: true
    var.paths:
      - /var/log/activemq/activemq.log
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.8/filebeat-module-postgresql.html
- module: postgresql
  # All logs
  log:
    enabled: true
    var.paths:
      - /var/log/postgresql/postgresql.log
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.8/filebeat-module-traefik.html
- module: traefik
  access:
    enabled: true
    var.paths:
      - /var/log/traefik/access.log

filebeat.inputs:
- type: container
  paths: 
    - "/var/lib/docker/containers/*/*.log"
- type: log
  paths: 
    - "/var/log/xnat/*"
    - "/var/log/tomcat/*"

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

# - decode_json_fields:
#     fields: ["message"]
#     target: "json"
#     overwrite_keys: true

setup.kibana:
  host: "xnat-kibana"
    
output.elasticsearch:
  hosts: ["xnat-elastic:9200"]
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

logging.json: true
logging.metrics.enabled: false


