version: '2'

services:

    xnat-web:
        build:
            context: ./tomcat
            args:
                LOCALE: 'en_AU'
        ports:
            - "${TOMCAT_PORT}:8080"
        volumes:
            - ./webapps:/opt/tomcat/webapps
            - ./logs/xnat:/data/xnat/home/logs
            - ./logs/tomcat:/opt/tomcat/logs
            - ./plugins:/data/xnat/home/plugins
            - /var/run/docker.sock:/var/run/docker.sock
        expose:
            - "8080"
        links:
            - xnat-db

    xnat-db:
        build: ./postgres
        expose:
            - "5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    xnat-nginx:
        build: ./nginx
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ./logs/nginx:/var/log/nginx
        expose:
            - "80"
        links:
            - xnat-web

    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
        command:
            - '--config.file=/etc/prometheus/prometheus.yaml'
        ports:
            - '${PROMETHEUS_PORT}:9090'
        links:
            - cadvisor
            
    cadvisor:
        image: google/cadvisor
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        ports:
            - "${CADVISOR_PORT}:8080"
        expose:
            - ${CADVISOR_PORT}

