version: '3.7'

services:

    xnat-web:
        container_name: xnat-web-${XNAT_VERSION}
        build:
            context: ./tomcat
            args:
                LOCALE: 'en_US'
        ports:
            - "${TOMCAT_PORT}:8080"
        networks: [activemq-services]
        volumes: ["activemq-data:/opt/activemq/conf", "activemq-data:/data/activemq", "activemq-data:/var/log/activemq"]
        volumes:
            - ${TOMCAT_WEBAPPS}:/opt/tomcat/webapps
            - ${TOMCAT_LOGS}:/opt/tomcat/logs
            - ${XNAT_LOGS}:/data/xnat/home/logs
            - ${XNAT_CONFIG}:/data/xnat/home/config
            - ${XNAT_PLUGINS}:/data/xnat/home/plugins
            - ${XNAT_ARCHIVE}:/data/xnat/archive
            - ${XNAT_PIPELINE}=/data/xnat/pipeline
            - ${XNAT_PREARCHIVE}:/data/xnat/prearchive
            - /var/run/docker.sock:/var/run/docker.sock
        networks: [xnat-services]
        expose:
            - "8080"
        links:
            - xnat-db
        tty: true

    xnat-db:
        container_name: xnat-db-${XNAT_VERSION}
        build: ./postgres
        networks: [xnat-services]
        expose:
            - "5432"
        volumes:
            - ./data/postgres:/var/lib/postgresql/data

networks:
  xnat-services:
    driver: bridge

volumes:
  activemq-data: {}
  postgres-data: {}

networks:
  activemq-services:
    driver: bridge
