version: "3.7"

services:

  xnat-traefik:
    container_name: xnat-traefik
    image: "traefik:latest"
    networks:
      - xnat-services
    command:
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --api.insecure # Don't do that in production
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/config/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik-data/logs:/var/log
    labels:   
      - "traefik.enable=true"
      - "traefik.http.middlewares.strip-routes.stripprefix.prefixes=/pacs, /mq"
      - "traefik.http.middlewares.service-redirect.redirectregex.regex=^(https|http)://([a-zA-Z0-9_.-]+)/([a-zA-Z0-9_.-]+)$$"
      - "traefik.http.middlewares.service-redirect.redirectregex.replacement=$${1}://$${2}/$${3}/"
      - "traefik.http.middlewares.append-slash-to-training.redirectregex.regex=^(.+/training/[^/]+)$$"
      - "traefik.http.middlewares.append-slash-to-training.redirectregex.replacement=$${1}/"
      - "traefik.http.routers.traefik_dash.rule=PathPrefix(`/dashboard`)"
      - "traefik.http.routers.traefik_dash.middlewares=service-redirect@docker,strip-routes@docker"
      - "traefik.http.services.traefik_dash.loadbalancer.server.port=8080"

  xnat-activemq:
    container_name: xnat-activemq
    image: webcenter/activemq:5.14.3
    networks: [xnat-services]
    expose:
      - 8161
      - 61616
    ports:
      - "8161:8161"
      - "61616:61616"
    labels:
      - "traefik.http.routers.activemq.rule=PathPrefix(`/mq`)"
      - "traefik.http.services.activemq.loadbalancer.server.port=8161"
      - "traefik.http.routers.activemq.middlewares=service-redirect@docker,strip-routes@docker"
    volumes:
      - ./activemq-data/data:/data/activemq
      - ./activemq-data/logs:/var/log/activemq
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
      ACTIVEMQ_WRITE_LOGIN: write
      ACTIVEMQ_WRITE_PASSWORD: password
      ACTIVEMQ_READ_LOGIN: read
      ACTIVEMQ_READ_PASSWORD: password
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: password
      ACTIVEMQ_STATIC_TOPICS: archive;prearchive;automation
      ACTIVEMQ_STATIC_QUEUES: defaultRequest;automatedScriptRequest;moveStoredFileRequest;prearchiveOperationRequest;initializeGroupRequest;dicomInboxImportRequest
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 1024
      ACTIVEMQ_MAX_MEMORY: 4096

  xnat-db:
    container_name: xnat-db
    image: postgres:12.2-alpine
    networks: [xnat-services]
    environment:
      POSTGRES_PASSWORD: ${XNAT_DATASOURCE_ADMIN_PASSWORD}
    expose:
      - 5432
    volumes:
      - ./postgres-data/data:/var/lib/postgresql/data
      - ./postgres-data/logs:/var/log/postgresql
      - ./postgres/XNAT.sql:/docker-entrypoint-initdb.d/XNAT.sql
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: "postgres -c 'config_file=/etc/postgresql/postgresql.conf'"

networks:
  xnat-services:
    name: xnat-services
    driver: bridge

